//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Delegation
{
    public string DelegationID { get; set; }
    public string DepartmentHeadID { get; set; }
    public string CoveringHeadID { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }

    public virtual Staff Staff { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.DisbursementLogs = new HashSet<DisbursementLog>();
        this.OutstandingRequests = new HashSet<OutstandingRequest>();
        this.Staffs = new HashSet<Staff>();
        this.TransactionLogs = new HashSet<TransactionLog>();
    }

    public string DepartmentID { get; set; }
    public string Collection_Point { get; set; }
    public string DepartmentName { get; set; }
    public string ContactName { get; set; }
    public string Telephone { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DisbursementLog> DisbursementLogs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OutstandingRequest> OutstandingRequests { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Staff> Staffs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
}

public partial class DisbursementLog
{
    public int DisbursementID { get; set; }
    public string ItemID { get; set; }
    public string DepartmentID { get; set; }
    public System.DateTime DateTime { get; set; }
    public int NeededNumber { get; set; }
    public int RetrivedNumber { get; set; }
    public int GivenNumber { get; set; }
    public string Flag { get; set; }
    public string ClerkID { get; set; }

    public virtual Department Department { get; set; }
    public virtual Item Item { get; set; }
    public virtual Staff Staff { get; set; }
}

public partial class Discrepancy
{
    public string DiscrepancyID { get; set; }
    public string ItemID { get; set; }
    public int Quantity { get; set; }
    public string Reason { get; set; }
    public string Status { get; set; }
    public string Comment { get; set; }
    public string RequestLog { get; set; }
    public System.DateTime Date { get; set; }
    public string UserID { get; set; }

    public virtual Item Item { get; set; }
    public virtual Staff Staff { get; set; }
}

public partial class Item
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {
        this.DisbursementLogs = new HashSet<DisbursementLog>();
        this.Discrepancies = new HashSet<Discrepancy>();
        this.Orders = new HashSet<Order>();
        this.OutstandingRequests = new HashSet<OutstandingRequest>();
        this.RequestDetails = new HashSet<RequestDetail>();
        this.SupplyDetails = new HashSet<SupplyDetail>();
        this.TransactionLogs = new HashSet<TransactionLog>();
    }

    public string ItemID { get; set; }
    public string Description { get; set; }
    public string Category { get; set; }
    public int InStock { get; set; }
    public string BinNumber { get; set; }
    public string UOM { get; set; }
    public int ReorderLevel { get; set; }
    public int ReorderQty { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DisbursementLog> DisbursementLogs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Discrepancy> Discrepancies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OutstandingRequest> OutstandingRequests { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RequestDetail> RequestDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SupplyDetail> SupplyDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
}

public partial class Notification
{
    public int NotificationID { get; set; }
    public string UserID { get; set; }
    public string Subject { get; set; }
    public string Message { get; set; }
    public string Status { get; set; }
    public System.DateTime Date { get; set; }

    public virtual Staff Staff { get; set; }
}

public partial class Order
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
    }

    public string OrderID { get; set; }
    public string ItemID { get; set; }
    public int TotalQty { get; set; }
    public string Justification { get; set; }
    public string Status { get; set; }
    public System.DateTime OrderDate { get; set; }
    public string UserID { get; set; }
    public string Comment { get; set; }
    public string RequestLog { get; set; }

    public virtual Item Item { get; set; }
    public virtual Staff Staff { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
}

public partial class OrderDetail
{
    public string PurchaseOrderID { get; set; }
    public string OrderID { get; set; }
    public string SupplierID { get; set; }
    public int OrderQty { get; set; }
    public int ReceivedQty { get; set; }

    public virtual Order Order { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class OutstandingRequest
{
    public string ItemID { get; set; }
    public string DepartmentID { get; set; }
    public int OutstandingQty { get; set; }

    public virtual Department Department { get; set; }
    public virtual Item Item { get; set; }
}

public partial class Request
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Request()
    {
        this.RequestDetails = new HashSet<RequestDetail>();
    }

    public string RequestID { get; set; }
    public System.DateTime RequestDate { get; set; }
    public string UserID { get; set; }
    public string RequestLog { get; set; }
    public string Comment { get; set; }

    public virtual Staff Staff { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RequestDetail> RequestDetails { get; set; }
}

public partial class RequestDetail
{
    public string RequestID { get; set; }
    public string ItemID { get; set; }
    public int RequestQty { get; set; }
    public int RetrievedQty { get; set; }
    public string Status { get; set; }

    public virtual Item Item { get; set; }
    public virtual Request Request { get; set; }
}

public partial class Staff
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Staff()
    {
        this.Delegations = new HashSet<Delegation>();
        this.DisbursementLogs = new HashSet<DisbursementLog>();
        this.Discrepancies = new HashSet<Discrepancy>();
        this.Notifications = new HashSet<Notification>();
        this.Orders = new HashSet<Order>();
        this.Requests = new HashSet<Request>();
    }

    public string UserID { get; set; }
    public string DepartmentID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Delegation> Delegations { get; set; }
    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<DisbursementLog> DisbursementLogs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Discrepancy> Discrepancies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Notification> Notifications { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Order> Orders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Request> Requests { get; set; }
}

public partial class Supplier
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {
        this.OrderDetails = new HashSet<OrderDetail>();
        this.SupplyDetails = new HashSet<SupplyDetail>();
    }

    public string SupplierID { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string SupplierName { get; set; }
    public string GSTRegistrationNo { get; set; }
    public string ContactName { get; set; }
    public string FaxNo { get; set; }
    public string Address { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SupplyDetail> SupplyDetails { get; set; }
}

public partial class SupplyDetail
{
    public string ItemID { get; set; }
    public string SupplierID { get; set; }
    public decimal Price { get; set; }
    public int Priority { get; set; }

    public virtual Item Item { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class TransactionLog
{
    public int TransactionID { get; set; }
    public string DepartmentID { get; set; }
    public string ItemID { get; set; }
    public Nullable<System.DateTime> DateTime { get; set; }
    public Nullable<int> RequestQty { get; set; }
    public Nullable<int> ReceiveQty { get; set; }
    public string Flag { get; set; }

    public virtual Department Department { get; set; }
    public virtual Item Item { get; set; }
}
